# Generated by Django 3.2 on 2022-04-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220421_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
