# Generated by Django 3.2 on 2022-04-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
