# Generated by Django 3.2 on 2022-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
